#         Powered by TabooLib 5.0         #


name: ${name}
main: ${main}
version: ${version}
authors: [ '冰上云梦' ]
softdepend: [ Essentials ]
depend: [ Vault ]
api-version: 1.13

lib-download: true
lib-version: ${libVersion}
loader-version: ${loaderVersion}
